security:
    # ...
    firewalls:
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_livre_index # Route de redirection après une connexion réussie
            logout:
                path: app_logout
                target: app_login # Redirection après la déconnexion

    access_control:
        # Définis ici tes règles de restriction d'accès si nécessaire
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }